make adaptive to header
an4morph/construct-frontend pull request #15
Opened 2023-04-12 03:41 UTC by aaidarov-triplea

2023-04-14 14:59 UTC, an4morph requested changes

2023-04-14 14:59 UTC, an4morph commented on src/components/icons/dev.jsx
> +export const DevBurgerIcon = ({ className }) => {
Приставка Dev к названию иконки не нужна

2023-04-14 14:59 UTC, an4morph commented on src/components/header/index.jsx
> +  ${media.xs`
media.xs добавлять не нужно для верстки mobile first.
Вот так бы все работало
> const LogoutButton = styled(Button)`
  margin-left: 40px;
  display: none;
  ${media.sm
    display: block;
  }

2023-04-14 14:59 UTC, an4morph commented on src/components/header/index.jsx
> +  ${media.sm`
sm слишком маленький брейкпоинт. По условию в задаче был больше

2023-04-14 14:59 UTC, an4morph commented on src/components/header/index.jsx
> +  ${media.xs`
нет нужды вот так вручную прятать каждый элемент. Спрячьте сразу весь блок в котором все лежит, а бургер положите в другой блок

2023-04-14 14:59 UTC, an4morph commented on src/components/header/index.jsx
> +
не нужно отделять блок отступами, будто он какой-то особенный от других

2023-04-17 10:05 UTC, aaidarov-triplea commented
все исправил проверите

2023-04-17 10:07 UTC, an4morph approved these changes

2023-04-17 10:07 UTC, merged